name: Push latest
on:
  push:
    branches:
      - main

jobs:
  push:
    name: Push :latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: nadiamoe
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          TAG=nadiamoe/netdbg
          docker build . -t $TAG
          docker push $TAG
