name: Push latest
on:
  push:
    branches:
      - main

jobs:
  push:
    name: Push :latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: nadiamoe
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          TAG=nadiamoe/netdbg
          docker build . -t $TAG
          docker push $TAG
